### ISSUE TITLE
Question about feature extraction method

### ISSUE THREAD

**Issue by chewry** [danieljf24/dual_encoding#4]
Hello. I'm trying to evaluate some model on the pre-computed MSR-VTT dataset that you provided.
But the result was on par with the random selection.
In the process of analyzing the cause, I think that there is a difference in the visual feature extraction step. 

Can you tell me which framework (TF, Keras, PyTorch...) and weight source you used in the visual feature extraction stage? Then I can analyze and experiment your research under the _same conditions_ with other models.

Thank you in advance!

**Comment by danieljf24** [comment]
I recommend utilizing our provided features to train your own model, which makes the performance comparison fair. Besides, we used MXNet with its provided ResNet152 model trained on ImageNet with 1k categories.

**Comment by nbravohack** [comment]
Hello @danieljf24 
What Resnext-101 model did you use?

Thanks you very much
