### ISSUE TITLE
 ./do_test_dual_encoding_msrvtt10ktest.sh: 没有那个文件或目录

### ISSUE THREAD

**Issue by zhufeng12345** [danieljf24/dual_encoding#8]
Hello, can I get your help? when I .run ./do_all.sh msrvtt10ktrain msrvtt10kval msrvtt10ktest full ， It will show that there is no folder

**Comment by danieljf24** [comment]
Did you put the dataset in $HOME/VisualSearch ?

**Comment by zhufeng12345** [comment]
Thank you very much ，I've put the folder in this location, and when I run this file, it displays “No such file or directory:/home/dl/ViaualSearch/msrvtt10ktriain.caption.txt". Finally, the word_vocab_5.pkl was not generated

**Comment by danieljf24** [comment]
msrvtt10ktriain.caption.txt is located in /home/dl/ViaualSearch/msrvtt10ktriain/TextData/msrvtt10ktriain.caption.txt

**Comment by zhufeng12345** [comment]
OK，Thank you very much.
